import { Profile, CURRENT_SCHEMA_VERSION } from "core";

export const standardProfile: Profile = {
	version: CURRENT_SCHEMA_VERSION,
	id: "standard-profile",
	name: "Standard User",
	enabledDomains: ["*"],
	rules: [
		{
			id: "t1",
			name: "Given Name",
			content: "John",
			keywords: ["given name", "first name", "firstName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t2",
			name: "Family Name",
			content: "Doe",
			keywords: ["family name", "last name", "lastName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t3",
			name: "Email",
			content: "john.doe@example.com",
			keywords: ["email", "e-mail", "emailAddress"],
			matchtype: "contains",
			inputtype: "email",
		},
		{
			id: "t4",
			name: "Phone Number",
			content: "+15551234567",
			keywords: ["phone number", "phoneNumber", "mobile", "phone"],
			matchtype: "contains",
			inputtype: "tel",
		},
		{
			id: "t5",
			name: "Full Name",
			content: "John Doe",
			keywords: ["full name"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w4",
			name: "City",
			content: "Metropolis",
			keywords: ["city", "town"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w5",
			name: "Postal Code",
			content: "12345",
			keywords: ["postalCode", "zip code", "postcode"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we1",
			name: "Job Title",
			content: "Senior Software Engineer",
			keywords: ["jobTitle", "job title", "position"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we2",
			name: "Company",
			content: "Acme Corp",
			keywords: ["companyName", "company", "employer"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we4",
			name: "School or University",
			content: "State University",
			keywords: ["schoolName", "school", "university", "college"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we9",
			name: "LinkedIn",
			content: "https://linkedin.com/in/johndoe",
			keywords: ["linkedInAccount", "linkedin"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we11",
			name: "GitHub",
			content: "https://github.com/johndoe",
			keywords: ["github"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we10",
			name: "Website / Portfolio",
			content: "https://johndoe.dev",
			keywords: ["website", "portfolio", "personal link"],
			matchtype: "contains",
			inputtype: "text",
		},
	],
};

export const alternativeProfile: Profile = {
	version: CURRENT_SCHEMA_VERSION,
	id: "alternative-profile",
	name: "Alternative User",
	enabledDomains: ["*"],
	rules: [
		{
			id: "t1",
			name: "Given Name",
			content: "Jane",
			keywords: ["given name", "first name", "firstName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t2",
			name: "Family Name",
			content: "Smith",
			keywords: ["family name", "last name", "lastName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t3",
			name: "Email",
			content: "jane.smith@example.co.uk",
			keywords: ["email", "e-mail", "emailAddress"],
			matchtype: "contains",
			inputtype: "email",
		},
		{
			id: "t4",
			name: "Phone Number",
			content: "+441234567890",
			keywords: ["phone number", "phoneNumber", "mobile", "phone"],
			matchtype: "contains",
			inputtype: "tel",
		},
		{
			id: "t5",
			name: "Full Name",
			content: "Jane Smith",
			keywords: ["full name"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w4",
			name: "City",
			content: "London",
			keywords: ["city", "town"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w5",
			name: "Postal Code",
			content: "SW1A 1AA",
			keywords: ["postalCode", "zip code", "postcode"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we1",
			name: "Job Title",
			content: "Product Manager",
			keywords: ["jobTitle", "job title", "position"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we2",
			name: "Company",
			content: "Globex",
			keywords: ["companyName", "company", "employer"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we4",
			name: "School or University",
			content: "Oxford University",
			keywords: ["schoolName", "school", "university", "college"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we9",
			name: "LinkedIn",
			content: "https://linkedin.com/in/janesmith",
			keywords: ["linkedInAccount", "linkedin"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we11",
			name: "GitHub",
			content: "https://github.com/janesmith",
			keywords: ["github"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we10",
			name: "Website / Portfolio",
			content: "https://janesmith.pm",
			keywords: ["website", "portfolio", "personal link"],
			matchtype: "contains",
			inputtype: "text",
		},
	],
};

export const testProfiles = [standardProfile, alternativeProfile];
