import { CURRENT_SCHEMA_VERSION } from "./constants";
import { Profile, Rule } from "./types";

export const DEFAULT_RULE: Omit<Rule, "id"> = {
	name: "New Field",
	content: "",
	keywords: [],
	matchtype: "fuzzy",
	inputtype: "any",
};

export const DEFAULT_PROFILE: Omit<Profile, "id"> = {
	version: CURRENT_SCHEMA_VERSION,
	name: "New Profile",
	enabledDomains: ["*"],
	rules: [
		{
			id: "1",
			name: "Full Name",
			content: "",
			keywords: ["name", "full name"],
			matchtype: "fuzzy",
			inputtype: "any",
		},
		{
			id: "2",
			name: "Email",
			content: "",
			keywords: ["email", "e-mail"],
			matchtype: "fuzzy",
			inputtype: "any",
		},
		{
			id: "3",
			name: "Phone",
			content: "",
			keywords: ["phone", "mobile"],
			matchtype: "fuzzy",
			inputtype: "any",
		},
	],
};

export const PROFILE_TEMPLATES: Profile[] = [
	{
		version: CURRENT_SCHEMA_VERSION,
		id: "basic-info",
		name: "Basic Information",
		enabledDomains: ["*"],
		rules: [
			{
				id: "t1",
				name: "Given Name",
				content: "",
				keywords: ["given name", "first name", "firstName"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "t2",
				name: "Family Name",
				content: "",
				keywords: ["family name", "last name", "lastName"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "t3",
				name: "Email",
				content: "",
				keywords: ["email", "e-mail", "emailAddress"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "t4",
				name: "Phone Number",
				content: "",
				keywords: ["phone number", "phoneNumber", "mobile", "phone"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "t5",
				name: "Country",
				content: "",
				keywords: ["country", "nation"],
				matchtype: "fuzzy",
				inputtype: "select",
			},
		],
	},
	{
		version: CURRENT_SCHEMA_VERSION,
		id: "workday-full",
		name: "Workday Standard",
		enabledDomains: ["*"],
		rules: [
			{
				id: "w1",
				name: "Given Name",
				content: "",
				keywords: ["legalName--firstName", "given name", "first name"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w2",
				name: "Family Name",
				content: "",
				keywords: ["legalName--lastName", "family name", "last name"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w3",
				name: "Address Line 1",
				content: "",
				keywords: ["addressLine1", "address line 1", "street"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w4",
				name: "City",
				content: "",
				keywords: ["city", "town"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w5",
				name: "Postal Code",
				content: "",
				keywords: ["postalCode", "zip code", "postcode"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w6",
				name: "Phone Number",
				content: "",
				keywords: ["phoneNumber", "phone number", "mobile", "phone"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "w7",
				name: "How Did You Hear About Us?",
				content: "",
				keywords: ["source", "how did you hear"],
				matchtype: "fuzzy",
				inputtype: "any",
			},
			{
				id: "w_country",
				name: "Country",
				content: "",
				keywords: ["country", "nation"],
				matchtype: "fuzzy",
				inputtype: "select",
			},
			{
				id: "w8",
				name: "Previous Worker",
				content: "false",
				keywords: ["candidateIsPreviousWorker", "worked for", "previous worker"],
				matchtype: "fuzzy",
				inputtype: "any",
			},
		],
	},
	{
		version: CURRENT_SCHEMA_VERSION,
		id: "workday-experience",
		name: "Workday Experience",
		enabledDomains: ["*"],
		rules: [
			{
				id: "we1",
				name: "Job Title",
				content: "",
				keywords: ["jobTitle", "job title", "position"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we2",
				name: "Company",
				content: "",
				keywords: ["companyName", "company", "employer"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we2_loc",
				name: "Location",
				content: "",
				keywords: ["location", "company location"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we2_start_month",
				name: "Work Start Month",
				content: "",
				keywords: ["startDate dateSectionMonth", "from month"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we2_start_year",
				name: "Work Start Year",
				content: "",
				keywords: ["startDate dateSectionYear", "from year"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we2_end_month",
				name: "Work End Month",
				content: "",
				keywords: ["endDate dateSectionMonth", "to month"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we2_end_year",
				name: "Work End Year",
				content: "",
				keywords: ["endDate dateSectionYear", "to year"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we3",
				name: "Role Description",
				content: "",
				keywords: ["roleDescription", "role description", "responsibilities", "summary"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we4",
				name: "School or University",
				content: "",
				keywords: ["schoolName", "school", "university", "college"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we5",
				name: "Degree",
				content: "",
				keywords: ["degree"],
				matchtype: "fuzzy",
				inputtype: "select",
			},
			{
				id: "we6",
				name: "Field of Study",
				content: "",
				keywords: ["fieldOfStudy", "field of study", "major"],
				matchtype: "fuzzy",
				inputtype: "select",
			},
			{
				id: "we7",
				name: "GPA",
				content: "",
				keywords: ["gradeAverage", "gpa", "overall result"],
				matchtype: "fuzzy",
				inputtype: "number",
			},
			{
				id: "we7_start_year",
				name: "Education Start Year",
				content: "",
				keywords: ["firstYearAttended dateSectionYear", "education from year"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we7_end_year",
				name: "Education End Year",
				content: "",
				keywords: ["lastYearAttended dateSectionYear", "education to year"],
				matchtype: "fuzzy",
				inputtype: "spinbox",
			},
			{
				id: "we8",
				name: "Skills",
				content: "",
				keywords: ["skills", "type to add skills"],
				matchtype: "fuzzy",
				inputtype: "multiselect",
			},
			{
				id: "we9",
				name: "LinkedIn",
				content: "",
				keywords: ["linkedInAccount", "linkedin"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
			{
				id: "we10",
				name: "Website / Portfolio",
				content: "",
				keywords: ["website", "portfolio", "personal link"],
				matchtype: "fuzzy",
				inputtype: "text",
			},
		],
	},
];
