import { CURRENT_SCHEMA_VERSION, Profile } from "./types";

export const mockProfile: Profile = {
	version: CURRENT_SCHEMA_VERSION,
	id: "test-profile",
	name: "Test User",
	enabledDomains: ["*"],
	rules: [
		// Basic Information (from PROFILE_TEMPLATES: basic-info)
		{
			id: "t1",
			name: "Given Name",
			content: "John",
			keywords: ["given name", "first name", "firstName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t2",
			name: "Family Name",
			content: "Doe",
			keywords: ["family name", "last name", "lastName"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "t3",
			name: "Email",
			content: "john.doe@example.com",
			keywords: ["email", "e-mail", "emailAddress"],
			matchtype: "contains",
			inputtype: "email",
		},
		{
			id: "t4",
			name: "Phone Number",
			content: "+15551234567",
			keywords: ["phone number", "phoneNumber", "mobile"],
			matchtype: "contains",
			inputtype: "tel",
		},

		// Workday - Full (selected fields)
		{
			id: "w3",
			name: "Address Line 1",
			content: "123 Main St",
			keywords: ["addressLine1", "address line 1", "street"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w4",
			name: "City",
			content: "Metropolis",
			keywords: ["city", "town"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w5",
			name: "Postal Code",
			content: "12345",
			keywords: ["postalCode", "zip code", "postcode"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w7",
			name: "How Did You Hear About Us?",
			content: "LinkedIn",
			keywords: ["source", "how did you hear"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "w8",
			name: "Previous Worker",
			content: "false",
			keywords: ["candidateIsPreviousWorker", "worked for", "previous worker"],
			matchtype: "contains",
			inputtype: "any",
		},

		// Workday - Experience (from PROFILE_TEMPLATES: workday-experience)
		{
			id: "we1",
			name: "Job Title",
			content: "Senior Software Engineer",
			keywords: ["jobTitle", "job title", "position"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we2",
			name: "Company",
			content: "Acme Corp",
			keywords: ["companyName", "company", "employer"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we2_loc",
			name: "Location",
			content: "Remote",
			keywords: ["location", "company location"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we2_start_month",
			name: "Work Start Month",
			content: "06",
			keywords: ["startDate dateSectionMonth", "from month"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we2_start_year",
			name: "Work Start Year",
			content: "2016",
			keywords: ["startDate dateSectionYear", "from year"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we2_end_month",
			name: "Work End Month",
			content: "06",
			keywords: ["endDate dateSectionMonth", "to month"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we2_end_year",
			name: "Work End Year",
			content: "2024",
			keywords: ["endDate dateSectionYear", "to year"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we3",
			name: "Role Description",
			content: "Built scalable web applications and led a team of engineers.",
			keywords: ["roleDescription", "role description", "responsibilities", "summary"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we4",
			name: "School or University",
			content: "State University",
			keywords: ["schoolName", "school", "university", "college"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we5",
			name: "Degree",
			content: "Bachelor of Science",
			keywords: ["degree"],
			matchtype: "contains",
			inputtype: "select",
		},
		{
			id: "we6",
			name: "Field of Study",
			content: "Computer Science",
			keywords: ["fieldOfStudy", "field of study", "major"],
			matchtype: "contains",
			inputtype: "select",
		},
		{
			id: "we7",
			name: "GPA",
			content: "3.8",
			keywords: ["gradeAverage", "gpa", "overall result"],
			matchtype: "contains",
			inputtype: "number",
		},
		{
			id: "we7_start_year",
			name: "Education Start Year",
			content: "2012",
			keywords: ["firstYearAttended dateSectionYear", "education from year"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we7_end_year",
			name: "Education End Year",
			content: "2016",
			keywords: ["lastYearAttended dateSectionYear", "education to year"],
			matchtype: "contains",
			inputtype: "spinbox",
		},
		{
			id: "we8",
			name: "Skills",
			content: "JavaScript, TypeScript, React",
			keywords: ["skills", "type to add skills"],
			matchtype: "contains",
			inputtype: "multiselect",
		},
		{
			id: "we9",
			name: "LinkedIn",
			content: "https://linkedin.com/in/johndoe",
			keywords: ["linkedInAccount", "linkedin"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "we10",
			name: "Website / Portfolio",
			content: "https://johndoe.dev",
			keywords: ["website", "portfolio", "personal link"],
			matchtype: "contains",
			inputtype: "text",
		},
		{
			id: "bio",
			name: "Bio",
			content: "I am a senior software engineer with 10 years of experience.",
			keywords: ["bio", "biography", "summary"],
			matchtype: "contains",
			inputtype: "textarea",
		},
	],
};
